### ISSUE TITLE
QuakeML Example is buggy

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [usgs/Quakeml#2]
The example (https://github.com/usgs/Quakeml/wiki/Focal-mechanism-example) seems to be lacking a tag in line 4. At least obspy and pyrocko refuse to parse that example without the following extended line 4:

```<q:quakeml xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:catalog="http://anss.org/xmlns/catalog/0.1" xmlns:q="http://quakeml.org/xmlns/quakeml/1.2">```

**Comment by jmfee-usgs** [comment]
Thanks for letting us know.  I corrected the example as you described.
